# Generated by Django 5.1.2 on 2024-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
